### ISSUE TITLE
out of range???

### ISSUE THREAD

**Issue by C640935471** [KikiLetGo/CyberControllerServer#9]
Traceback (most recent call last):
  File "c:\Cyber\CyberControllerServer\Controller.py", line 32, in <module>
    tcpServer = TcpServer()
  File "c:\Cyber\CyberControllerServer\TcpServer.py", line 12, in __init__
    hostip=sysinfo[2][2]
IndexError: list index out of range

how to solve this issue?

**Comment by C640935471** [comment]
find it and change [2][2] to [2][0]
